name = "MSBuild Project"
code_fence_block_name = "xml"
grammar = "xml"
path_suffixes = ["csproj", "props", "targets"]
autoclose_before = ">})"
block_comment = { start = "<!--", prefix = "", end = "-->", tab_size = 0 }
wrap_characters = { start_prefix = "<", start_suffix = ">", end_prefix = "</", end_suffix = ">" }
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "<", end = ">", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "!--", end = " --", close = true, newline = false, not_in = ["comment", "string"] },
]
completion_query_characters = ["-"]

[jsx_tag_auto_close]
open_tag_node_name = "STag"
close_tag_node_name = "ETag"
jsx_element_node_name = "element"
tag_name_node_name = "Name"
tag_name_node_name_alternates = ["_start_tag_name", "_end_tag_name"]

[overrides.default]
linked_edit_characters = ["-"]
